name: MangoStructures
main: com.kylantraynor.mangostructures.MangoStructures
version: ${project.version}
description: Plugin handling multi-block structures for Project Mango.
commands:
  chimney:
    description: Access all the chimney commands.
    permission: mangostructures.chimney